### ISSUE TITLE
302 Location Url Error

### ISSUE THREAD

**Issue by DeHby** [Danny-Dasilva/CycleTLS#323]
### Description

GET https://t.cn/

The response is: Location: http://weibo.com/
But according to the packet capture logs, it was found that the redirected URL was incorrect
![image](https://github.com/Danny-Dasilva/CycleTLS/assets/47233058/83abfe31-e58b-4838-9bec-221bd52ee50e)
![image](https://github.com/Danny-Dasilva/CycleTLS/assets/47233058/17cc8b53-f6ff-4884-80b7-f7070e55504e)
Using Winnet's packet capture logs:
![image](https://github.com/Danny-Dasilva/CycleTLS/assets/47233058/cf00cd71-7396-42f3-ab3c-78545c4379e8)

go version go1.21.6 windows/amd64

### Issue Type

Bug

### Operating System

Windows 10

### Node Version

Other

### Golang Version

Other

**Comment by lif0** [comment]
This is because CycleTLS does not support more than one redirection.
If you open https://weibo.com/, the first you will be redirected to https://weibo.com/login;
Example: 
<img width="874" alt="image" src="https://github.com/Danny-Dasilva/CycleTLS/assets/22912194/0efb936a-9c82-49a9-9f57-08aac5f234da">

How fix that:
as long as you can use https://weibo.com/
<img width="534" alt="image" src="https://github.com/Danny-Dasilva/CycleTLS/assets/22912194/92520bef-4094-4b3a-b8b2-32841fcb0c3a">

**Comment by lif0** [comment]
@Danny-Dasilva I think i can fix that, what do you think?

**Comment by lif0** [comment]
@DeHby hey, bro, i was fixed that. PR: https://github.com/Danny-Dasilva/fhttp/pull/2

**Comment by Danny-Dasilva** [comment]
Changes have been merged and live in the 1.0.26 release
