### ISSUE TITLE
Akamai fingerprint

### ISSUE THREAD

**Issue by 89z** [Danny-Dasilva/CycleTLS#94]
Hope you don't mind, but I thought it would be good to start a new issue for this. I am concerned, because the implementation that was linked:

https://tls.peet.ws/api/clean

Doesn't give any info of the author, so we could end up with a `ja3er.com` situation all over again. I did find the owners main site:

https://peet.ws

but the listed Twitter and Discord info is all bogus. I did send a message to the owner via Matrix, if that doesn't work, I can try email as well. Here is link to the spec:

https://blackhat.com/docs/eu-17/materials/eu-17-Shuster-Passive-Fingerprinting-Of-HTTP2-Clients-wp.pdf

**Comment by 89z** [comment]
https://github.com/Danny-Dasilva/CycleTLS/issues/70

**Comment by 89z** [comment]
Here is link to the spec:

https://blackhat.com/docs/eu-17/materials/eu-17-Shuster-Passive-Fingerprinting-Of-HTTP2-Clients-wp.pdf

**Comment by 89z** [comment]
Here is something interesting. The Akamai paper says its for HTTP/2, which after testing seems to mean HTTP/2 only:

~~~
> curl --http1.1 https://tls.peet.ws/api/clean
{
  "ja3": "771,4866-4867-4865-49196-49200-159-52393-52392-52394-49195-49199-158-49188-49192-107-49187-49191-103-49162-49172-57-49161-49171-51-157-156-61-60-53-47-255,0-11-10-13172-16-22-23-49-13-43-45-51,29-23-30-25-24,0-1-2",
  "ja3_hash": "ba730f97dcd1122e74e65411e68f1b40",
  "akamai": "-",
  "akamai_hash": "-"
}
~~~

**Comment by 89z** [comment]
Same result with Go as well:

~~~go
package main

import (
   "crypto/tls"
   "net/http"
   "os"
)

func main() {
   req, err := http.NewRequest("GET", "https://tls.peet.ws/api/clean", nil)
   if err != nil {
      panic(err)
   }
   tr := http.Transport{
      TLSNextProto: make(map[string]func(string, *tls.Conn) http.RoundTripper),
   }
   res, err := tr.RoundTrip(req)
   if err != nil {
      panic(err)
   }
   defer res.Body.Close()
   os.Stdout.ReadFrom(res.Body)
}
~~~

**Comment by 89z** [comment]
Based on the HTTP/2 requirement, I think I am no longer interested in this. I would have to modify my code to add HTTP/2 support. Example:

https://github.com/refraction-networking/utls/blob/9d36ce36584651b35280a1ef8fc57e15791820be/examples/examples.go#L417-L427

So in that case, supporting JA3 is simpler than supporting Akamai. I will leave this issue open, in case others want to discuss it

**Comment by jjsaunier** [comment]
If you are scared such service disapear, I maintain my own here and this can handle the load. 

* ja3 `https://tools.scrapfly.io/api/fp/ja3?extended=1`
* http2 `https://tools.scrapfly.io/api/fp/akamai?extended=1`

And yes the akamai is only http2, it's using the values from http2 frames `SETTINGS,WINDOW_UPDATE,PRIORITY,HEADERS` announced by the client, but it's easily spoofable with fhttp or by simply forking http2 lib and replace values

**Comment by 89z** [comment]
@jjsaunier is the source code public? Otherwise, its no different than the current solutions.

**Comment by jjsaunier** [comment]
no, but I'm not sure to understand then - what is your issue? the `17513` extension ?

**Comment by 89z** [comment]
This issue is about supporting Akamai fingerprint, in addition to JA3 fingerprint. If you have some server that returns these, that could be helpful, but only if the source code for that server is available. We already have a couple of servers that return JA3, the problem is that none of them are open source, and at least one is returning know bad JA3. So any further servers to be considered, would need to provide the source code. That way, if the new server had a problem or goes down, we can host locally, or rehost the code somewhere else.

With all due respect, without the server source code, other servers are not needed or wanted.

**Comment by jjsaunier** [comment]
oh, I don't store fingerprints, probably tls.peet.ws neither - and it's not working that way. Most of the people are testing bots against it, there is a high chance you build a biased database. You need to honey pot or drive traffic with legit browsers to feed it correctly - so it requires building a website or something to collect relevant fp and then filter with some simple stats, otherwise, it has no value. But you can build a database on your side using existing sensors (ja3er or whatever) without the source code of the sensor, the API returned all the info - so you can simply build a website, call the sensor from the client browser and store the information (HTTP headers/sensor data) - and then you can open source the csv if you want

**Comment by 89z** [comment]
I have blocked @jjsaunier as you seem to be providing nothing but off topic comments. You wont be able to comment further. You're welcome to contact me using my email in my profile, if you have an open source JA3 or Akamai implementation.

**Comment by wwhtrbbtt** [comment]
Hey, I just found out about this conversation. I am the owner of tls.peet.ws. There seems to be some confusion.

1. I wouldnt use the site in a testing suite. It often goes down, because the code is still pretty buggy.
2. Yes, it only works on http/2. I originally build the tool for cloudflare, and they will trust your client more if you use http/2, instead of http/1.1. You can use the standard golang TLS library, if your http/2 client sends the same data as chrome, cloudflare will trust you. That means they prioritize http/2 fingerprinting over TLS fingerprinting.
3. I should really update my website, the email is still maintained though.
4. I actually keep some logs of tls.peet.ws


Btw I love the work of you guys, keep it up. If you have any more questions, hit me up. Another great website for http/2 fingerprinting is https://tls.fxnatic.dev/

**Comment by 89z** [comment]
Hello. In response to above comment, and also private chat.

The `tls.peet.ws` and `tls.fxnatic.dev` servers are interesting, but we are looking for an open source solution at this time. The previous solution of `ja3er.com` was also closed source, which cause several problems. We have already found an open source server (tlshello.agwa.name and github.com/AGWA/tlshacks), but I am interested in other options as well, assuming they are open source.

**Comment by Danny-Dasilva** [comment]
I cannot thank you enough for open sourcing your http2 server. 

For `1.` don't worry about it, the benefit of the code being open source is I can test against a local version rather than hitting your server (e.g. directly build it into the test suite). It also helps the more offensive debugging for unsupported extensions. 

For `2.` no worries this repo supports http/2 and as you stated that's more valuable

Again super grateful for your contribution.

**Comment by Danny-Dasilva** [comment]
> Btw I love the work of you guys, keep it up. If you have any more questions, hit me up. Another great website for http/2 fingerprinting is https://tls.fxnatic.dev/

I cannot thank you enough for open sourcing your http2 server. 

For `1.` don't worry about it, the benefit of the code being open source is I can test against a local version rather than hitting your server (e.g. directly build it into the test suite). It also helps the more offensive debugging for unsupported extensions. 

For `2.` no worries this repo supports http/2 and as you stated that's more valuable

Again super grateful for your contribution.
